import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./ globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import ClientProvider from "@/components/ClientProvider";
import FirebaseAuthProvidee from "@/components/FirebaseAuthProvidee";
import SubscriptioProvider from "@/components/SubscriptioProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat with Your Language",
  description: "Generated by Digistacks",
};

import "../../globals.css";
export default function ChatsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <div className=" w-full flex ddd flex-col max-w-6xl min-h-screen bg-green-900 mx-auto ">
        {children}
    </div>
  
  );
}
